global:
  aws:
    account: '222487244010'
    awsEsProxyRole: skfqa--default--es-access
    enabled: true
  dev: false
  dictionaryUrl: https://s3.amazonaws.com/dictionary-artifacts/kf-dictionary/develop/schema.json
  environment: skfqa
  externalSecrets:
    deploy: true
  hostname: gen3staging.kidsfirstdrc.org
  manifestGlobalExtraValues:
    kube_bucket: kube-skfqa-gen3
    logs_bucket: logs-skfqa-gen3
    maintenance_mode: 'off'
    netpolicy: 'on'
    sync_from_dbgap: 'False'
    useryaml_s3path: s3://kf-gen3-user/nonprd/user-nonprd.yaml
  portalApp: gitops
  postgres:
    dbCreate: false
  revproxyArn: arn:aws:acm:us-east-1:222487244010:certificate/d91de077-c452-4172-9f1e-c88c99feb9f0
indexd:
  autoscaling:
    enabled: true
    maxReplicas: 2
    minReplicas: 1
    targetCPUUtilizationPercentage: 40
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/indexd
    tag: '2025.01'
metadata:
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/metadata-service
    tag: '2025.01'
peregrine:
  autoscaling:
    enabled: true
    maxReplicas: 2
    minReplicas: 1
    targetCPUUtilizationPercentage: 40
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/peregrine
    tag: '2025.01'
revproxy:
  autoscaling:
    enabled: true
    maxReplicas: 2
    minReplicas: 1
    targetCPUUtilizationPercentage: 40
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/nginx
    tag: '2025.01'
sheepdog:
  autoscaling:
    enabled: true
    maxReplicas: 2
    minReplicas: 1
    targetCPUUtilizationPercentage: 40
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/sheepdog
    tag: '2025.01'
arborist:
  autoscaling:
    enabled: true
    maxReplicas: 2
    minReplicas: 1
    targetCPUUtilizationPercentage: 40
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/arborist
    tag: '2025.01'
audit:
  enabled: true
  externalSecrets:
    auditG3auto: skfqa-audit-g3auto
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/audit-service
    tag: '2025.01'
awshelper:
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/awshelper
    tag: '2025.01'
dashboard:
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/gen3-statics
    tag: '2025.01'
fence:
  autoscaling:
    enabled: true
    maxReplicas: 2
    minReplicas: 1
    targetCPUUtilizationPercentage: 40
  enabled: true
  externalSecrets:
    createK8sGoogleAppSecrets: true
    fenceConfig: skfqa-fence-config
    fenceJwtKeys: skfqa-fence-jwt
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/fence
    tag: '2025.01'
fluentd:
  enabled: true
  image:
    repository: fluent/fluentd-kubernetes-daemonset
    tag: v1.15.3-debian-cloudwatch-1.0
