cluster: emalinowskiv1
project: dev

eksClusterEndpoint: https://60E5A0594C0DD93E53A5D1DC91CD0C07.gr7.us-east-1.eks.amazonaws.com

accountNumber: "707767160287"

configuration:
  configurationRevision: feat/karpenter-1-0

alb-controller:
  enabled: true
  configuration:
    enabled: false

aws-s3-mountpoint:
  enabled: false
  configuration:
    enabled: false

calico:
  enabled: true
  configuration:
    enabled: false

coreDNS:
  enabled: true
  configuration:
    enabled: false

ebs-csi-driver:
  enabled: true
  configuration:
    enabled: false

fluentd:
  enabled: false
  configuration:
    enabled: false

kube-state-metrics:
  enabled: false
  configuration:
    enabled: false

grafana-alloy:
  enabled: false
  configuration:
    enabled: false

karpenter:
  enabled: true
  targetRevision: "1.0.8"
  configuration:
    enabled: false

karpenter-crds:
  amiSelectorName: "1-31-EKS-FIPS*"
  enabled: true
  selectorTag: emalinowskiv1
  migration: true

vpc-cni:
  enabled: true
  configuration:
    enabled: false
