arborist:
  replicaCount: 4
  autoscaling:
    enabled: false
    maxReplicas: 4
    minReplicas: 2
    targetCPUUtilizationPercentage: 40
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/arborist
    tag: '2026.01'
manifestservice:
  enabled: false
wts:
  enabled: false
audit:
  enabled: true
  externalSecrets:
    auditG3auto: dcf-staging-audit-g3auto
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/audit-service
    tag: '2026.01'
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::584476192960:role/dcf-staging--dcf-staging-helm--audit-sqs-receiver
aws-es-proxy:
  enabled: false
dashboard:
  dashboardConfig:
    bucket: dashboard-584476192960-dcf-staging-gen3
    prefix: nci-crdc-staging.datacommons.io
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/gen3-statics
    tag: '2026.01'
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::584476192960:role/dcf-staging--dcf-staging-helm--dashboard-access
datareplicate:
  enabled: true
  suspendCronjob: true
  externalSecrets:
    deploy: true
    googleCredsSecret: dcf-staging-gcloud-creds-secret
    dcfDataserviceSettingsSecret: dcf-staging-dcf-dataservice-settings-secrets
  resources:
    requests:
      cpu: '2'
      memory: 2Gi
    limits:
      memory: 8Gi
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/dcf-dataservice
    tag: 2.0.0
  awsBatchReplicateJob:
    enabled: true
    schedule: '*/30 * * * *'
    REGION: us-east-1
    THREAD_COUNT: 100
    MAX_RETRIES: 10
    MANIFEST_PATH: s3://test-data-replication-manifest/test_manifest_20251025.tsv
    JOB_QUEUE: nci-crdc-datacommons-io-bucket-replicate-19lv_queue_job
    JOB_DEFINITION: nci-crdc-datacommons-io-bucket-replicate-19lv-batch_job_definition
    OUTPUT_MANIFEST_BUCKET: test-data-replication-manifest
  batchServiceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::584476192960:role/dcf-staging--dcf-staging-helm--aws-batch-replicate-job
fence:
  FENCE_CONFIG_PUBLIC:
    S3_BUCKETS:
      multi-consent-test-bucket-kf:
        cred: fence_bot
        region: us-east-1
      nci-cbiit-caninedatacommons-file:
        cred: fence_bot
        region: us-east-1
      nci-cbiit-clinical-cmb-stage:
        cred: fence_bot
        region: us-east-1
      popsci-prod-files-dedicated-bucket:
        cred: fence_bot
        region: us-east-1
      tcga-protected-dcf-databucket-gen3:
        cred: fence_bot
      tcga-public-dcf-databucket-gen3:
        cred: fence_bot
      pdcdatastore-controlled:
        cred: fence_bot
        region: us-east-1
      dev-testing-bucketfor-matchdata:
        cred: fence_bot
        region: us-east-1
      dcf-staging-data-bucket:
        cred: fence_bot
        region: us-east-1
      crdc-ita:
        cred: fence_bot
        region: us-east-1
      crdc-itb:
        cred: fence_bot
        region: us-east-1
      123795211922-4920969-h59mrmjbpxe14b9gzq9tw5hkdwobruse1b-s3alias:
        cred: fence_bot
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::584476192960:role/dcf-staging--dcf-staging-helm--audit-sqs-sender
  replicaCount: 4
  autoscaling:
    enabled: false
    maxReplicas: 4
    minReplicas: 2
    targetCPUUtilizationPercentage: 40
  enabled: true
  externalSecrets:
    createK8sGoogleAppSecrets: false
    fenceConfig: dcf-staging-fence-config
    fenceGoogleAppCredsSecret: dcf-staging-fence-google-app-creds
    fenceGoogleStorageCredsSecret: dcf-staging-fence-google-storage-creds
    fenceJwtKeys: dcf-staging-fence-jwt
    fenceSshKeys: dcf-staging-fence-ssh-keys
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/fence
    tag: '2026.01'
  usersync:
    usersync: true
    syncFromDbgap: true
    sshKnownHosts: |
      sftp-private.ncbi.nlm.nih.gov ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCjEuJc/1pAQxGxwuk8s/1u7tDq2PiOqutAXNjPOl0BkOiJJnUa6gdRx5WcVd6HApPrw7RUvUXraOmc82Zlzeno6DkzTjLk3ztuRs1hNF3KKx044AxDC1Jew6pK96At3kAvStfamNbY8URB9tj0SF3rFQxLrWo8WfhFr9AU4SuY5S0A2a/njucmTim3vDRPbBFO7Dlz2dxzeKPBdUDB/NvmdPWHxkviXkqUby/QzjglAQTts5lNEMH8qaRcU/dnWYRKvY17RHGu9/gNf8Z9DvBg8TbU7Ek3MT5A9F3nw1ZcZe7M8L7JwIKgQUl1gzOBHFfC248YES9REQffLYPWOCy9
      sftp-private.ncbi.nlm.nih.gov ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAFM24A4pG3U+8HzCvEkm9SiEWHOAtQr/DFZd3bf7VYDCcg2FPpUvGRsiDSuzhzBo+eG00d6/6y8NCypWwjiMi1rYgBOh9YA0w/ruutXYMUUVzw361lTgjOBOZ/dt3gKkNgShwDd0e1hnjYk/E7jYc2YJv67ZFy9GzXCWR55LhS/7fGQ5w==
    userYamlS3Path: s3://cdis-gen3-users/dcfstaging-users/user.yaml
fluentd:
  enabled: true
  image:
    repository: fluent/fluentd-kubernetes-daemonset
    tag: v1.15.3-debian-cloudwatch-1.0
global:
  aws:
    account: '584476192960'
    awsEsProxyRole: dcf-staging--dcf-staging-helm--es-access
    enabled: true
    hatchery_role: dcf-staging--dcf-staging-helm--hatchery-sa
    secretStoreServiceAccount:
      enabled: true
      roleArn: arn:aws:iam::584476192960:role/dcf-staging-external-secrets-sa
    wafv2:
      enabled: true
      wafAclArn: arn:aws:wafv2:us-east-1:584476192960:regional/webacl/dcf-staging-waf/541a5a0d-56c7-4de0-af1e-d5c74cb2210f
  dev: false
  dictionaryUrl: https://s3.amazonaws.com/dictionary-artifacts/datadictionary/develop/schema.json
  dispatcherJobNum: '10'
  environment: dcf-staging
  externalSecrets:
    deploy: true
    createSlackWebhookSecret: true
    slackWebhookSecretName: dcf-staging-slack-webhook
  hostname: nci-crdc-staging.datacommons.io
  fenceURL: https://nci-crdc-staging.datacommons.io/user
  manifestGlobalExtraValues:
    indexd_single_table: 'true'
    kube_bucket: kube-dcf-staging-gen3
    logs_bucket: logs-dcf-staging-gen3
  portalApp: gitops
  postgres:
    dbCreate: false
  revproxyArn: arn:aws:acm:us-east-1:584476192960:certificate/b1f41138-54c0-4d5f-b2f3-7c5ebb20b555
indexd:
  defaultPrefix: dg.4DFC/
  useSingleTable: 'true'
  replicaCount: 4
  autoscaling:
    enabled: false
    maxReplicas: 4
    minReplicas: 2
    targetCPUUtilizationPercentage: 40
  enabled: true
  externalSecrets:
    serviceCreds: dcf-staging-indexd-service-creds
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/indexd
    tag: '2026.01'
metadata:
  replicaCount: 4
  autoscaling:
    enabled: false
    maxReplicas: 5
    minReplicas: 2
    targetCPUUtilizationPercentage: 40
  enabled: true
  esEndpoint: http://elasticsearch:9200
  externalSecrets:
    metadataG3auto: dcf-staging-metadata-g3auto
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/metadata-service
    tag: '2026.01'
mutatingWebhook:
  enabled: false
peregrine:
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/peregrine
    tag: '2026.01'
portal:
  enabled: true
  gitops:
    css: |-
      /* Hide Data Dictionary information */
      .footer__version-area > div:nth-child(1) {
        display: none;
      }
      /*Hide Google Login Option*/
      .login-page__entries:has(div.Google-Login) {
        display: none
      }
    json: |
      {
        "gaTrackingId": "undefined",
        "graphql": {
          "boardCounts": [
            {
              "graphql": "_case_count",
              "name": "Case",
              "plural": "Cases"
            },
            {
              "graphql": "_experiment_count",
              "name": "Experiment",
              "plural": "Experiments"
            },
            {
              "graphql": "_aliquot_count",
              "name": "Aliquot",
              "plural": "Aliquots"
            }
          ],
          "chartCounts": [
            {
              "graphql": "_case_count",
              "name": "Case"
            },
            {
              "graphql": "_experiment_count",
              "name": "Experiment"
            },
            {
              "graphql": "_aliquot_count",
              "name": "Aliquot"
            }
          ],
          "projectDetails": "boardCounts"
        },
        "components": {
          "appName": "NCI Data Commons Framework Services",
          "index": {
            "introduction": {
              "heading": "Data Commons",
              "text": "The NCI Data Commons Framework Services supports the management, analysis and sharing of data for the research community.",
              "link": "/submission"
            },
            "buttons": [
              {
                "name": "Access Data",
                "icon": "data-access",
                "body": "Use our selected tool to filter out the data you need.",
                "link": "/query",
                "label": "Query data"
              },
              {
                "name": "Submit Data",
                "icon": "data-submit",
                "body": "Submit Data based on the dictionary.",
                "link": "/submission",
                "label": "Submit data"
              }
            ]
          },
          "navigation": {
            "title": "NCI Data Commons Framework Services",
            "items": [
              {
                "icon": "profile",
                "link": "/identity",
                "name": "Profile",
                "tooltip": ""
              }
            ]
          },
          "topBar": {
            "items": [
              {
                "icon": "upload",
                "link": "/submission",
                "name": "Submit Data"
              },
              {
                "link": "https://nci-crdc-staging.datacommons.io/dashboard/Public/docs/redir_gen3.html",
                "name": "Documentation"
              }
            ]
          },
          "login": {
            "title": "NCI Data Commons Framework Services",
            "subTitle": "Explore, Analyze, and Share Data",
            "text": "The vision of DCFS is to make it easier to develop, operate, and interoperate data commons, data clouds, knowledge bases, and other resources for managing, analyzing, and sharing research data that can be part of a large data commons ecosystem.",
            "contact": "If you have any questions about access or the registration process, please contact ",
            "email": "dcf-support@gen3.org"
          },
          "certs": {
            "security_quiz": {
              "title": "BloodPAC User agreement",
              "description": "The agreement on what you can and need to do in a Commons.",
              "questions": [
                {
                  "name": "Things you can do after registration",
                  "question": "As a registered user, I can do the following things without any problem. Is it true or not:",
                  "options": [
                    "Browse public Project",
                    "Upload file",
                    "Download file",
                    "Invite people"
                  ],
                  "answer": 0,
                  "hint": "Some information about this question"
                },
                {
                  "name": "Things you need to do to become the registered user",
                  "question": "In order to be a register user, I must do the following things otherwise:",
                  "options": [
                    "Agree the user agreement",
                    "Accept a consent",
                    "None of them",
                    "Both of them"
                  ],
                  "answer": 2,
                  "hint": "Some information about this question"
                },
                {
                  "name": "Things you can do with data",
                  "question": "How can I share data with other people according to the policy of the commons",
                  "options": [
                    "I can not share data",
                    "I can only share data with BPA memebers",
                    "I can share data with family",
                    "I can share data with my wife"
                  ],
                  "answer": 1,
                  "hint": "Some information about this question"
                }
              ]
            }
          },
          "footerLogos": [
            {
              "src": "/src/img/gen3.png",
              "href": "https://nci-crdc-staging.datacommons.io/dashboard/Public/docs/redir_gen3_ctds.html",
              "alt": "Gen3 Data Commons"
            },
            {
              "src": "/src/img/createdby.png",
              "href": "https://nci-crdc-staging.datacommons.io/dashboard/Public/docs/redir_ctds.html",
              "alt": "Center for Translational Data Science at the University of Chicago"
            }
          ],
          "privacyPolicy": {
            "text": "",
            "routeHref": "",
            "footerHref": "",
            "file": ""
          },
            "footer": {
            "links": [
              {
                "text": "HHS Responsible Disclosure Form",
                "href": "https://www.hhs.gov/vulnerability-disclosure-policy/index.html"
              }
            ]
          }
        },
        "requiredCerts": [],
        "featureFlags": {
          "explorer": true,
          "analysis": false
        },
        "dataExplorerConfig": {
          "arrangerConfig": {
            "projectId": "search",
            "graphqlField": "subject",
            "index": "",
            "nodeCountField": "node_id"
          },
          "charts": {
            "project": {
              "chartType": "count",
              "title": "Projects"
            },
            "study": {
              "chartType": "count",
              "title": "Studies"
            },
            "file_type": {
              "chartType": "count",
              "title": "File Types"
            },
            "ethnicity": {
              "chartType": "stackedBar",
              "title": "Ethnicity"
            },
            "gender": {
              "chartType": "pie",
              "title": "Gender"
            },
            "race": {
              "chartType": "pie",
              "title": "Race"
            },
            "vital_status": {
              "chartType": "bar",
              "title": "Vital Status"
            }
          },
          "filters": {
            "tabs": [
              {
                "title": "Project",
                "fields": [
                  "project",
                  "study"
                ]
              },
              {
                "title": "Subject",
                "fields": [
                  "race",
                  "ethnicity",
                  "gender",
                  "vital_status"
                ]
              },
              {
                "title": "File",
                "fields": [
                  "file_type"
                ]
              }
            ]
          },
          "buttons": [
            {
              "enabled": true,
              "type": "data",
              "title": "Download All Data",
              "leftIcon": "user",
              "rightIcon": "download",
              "fileName": "data.json"
            },
            {
              "enabled": true,
              "type": "manifest",
              "title": "Download Manifest",
              "leftIcon": "datafile",
              "rightIcon": "download",
              "fileName": "manifest.json"
            }
          ],
          "table": {
            "enabled": true,
            "fields": [
              "project",
              "study",
              "race",
              "ethnicity",
              "gender",
              "vital_status",
              "whatever_lab_result_value",
              "file_count",
              "file_type",
              "file_format"
            ]
          }
        },
        "useArboristUI": false,
        "showArboristAuthzOnProfile": false,
        "showFenceAuthzOnProfile": true,
        "componentToResourceMapping": {}
      }
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/data-portal
    tag: '2026.01'
revproxy:
  replicaCount: 4
  autoscaling:
    enabled: false
    maxReplicas: 6
    minReplicas: 2
    targetCPUUtilizationPercentage: 40
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/nginx
    tag: '2026.01'
  ingress:
    aws:
      group: dcf-staging
sheepdog:
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/sheepdog
    tag: '2026.01'
sower:
  enabled: true
  externalSecrets:
    createK8sPelicanServiceSecret: true
    sowerjobsG3auto: dcf-staging-sower-jobs-g3auto
    createK8sSowerJobsSecret: false
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/sower
    tag: '2026.01'
  sowerConfig:
    - action: index-object-manifest
      activeDeadlineSeconds: 86400
      container:
        cpu-limit: '1'
        env:
          - name: GEN3_HOSTNAME
            valueFrom:
              configMapKeyRef:
                key: hostname
                name: manifest-global
        image: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/manifest-indexing:2026.01
        memory-limit: 1Gi
        name: job-task
        pull_policy: Always
        volumeMounts:
          - mountPath: /creds.json
            name: sower-jobs-creds-volume
            readOnly: true
            subPath: creds.json
      name: manifest-indexing
      restart_policy: Never
      serviceAccountName: jobs-nci-crdc-staging-datacommons-io
      volumes:
        - name: sower-jobs-creds-volume
          secret:
            secretName: sower-jobs-g3auto
    - action: download-indexd-manifest
      activeDeadlineSeconds: 86400
      container:
        cpu-limit: '1'
        env:
          - name: GEN3_HOSTNAME
            valueFrom:
              configMapKeyRef:
                key: hostname
                name: manifest-global
        image: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/download-indexd-manifest:2026.01
        memory-limit: 1Gi
        name: job-task
        pull_policy: Always
        volumeMounts:
          - mountPath: /creds.json
            name: sower-jobs-creds-volume
            readOnly: true
            subPath: creds.json
      name: indexd-manifest
      restart_policy: Never
      serviceAccountName: jobs-nci-crdc-staging-datacommons-io
      volumes:
        - name: sower-jobs-creds-volume
          secret:
            secretName: sower-jobs-g3auto
ssjdispatcher:
  enabled: true
  externalSecrets:
    credsFile: dcf-staging-ssjdispatcher-creds
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/ssjdispatcher
    tag: '2026.01'
  indexing: quay.io/cdis/indexs3client:2026.01
