arborist:
  replicaCount: 4
  autoscaling:
    enabled: false
    maxReplicas: 1
    minReplicas: 1
    targetCPUUtilizationPercentage: 40
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/arborist
    tag: '2025.12'
audit:
  enabled: true
  externalSecrets:
    auditG3auto: externaldata-audit-g3auto
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/audit-service
    tag: '2025.12'
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::205252583234:role/healprod--healexternaldata-helm--audit-sqs-receiver
aws-es-proxy:
  enabled: true
  esEndpoint: vpc-healprod-gen3-metadata-2-l6eifqrue4gqcmvc4u2dny3cdi.us-east-1.es.amazonaws.com
  image:
    repository: quay.io/cdis/aws-es-proxy
    tag: '0.8'
dashboard:
  dashboardConfig:
    bucket: dashboard-205252583234-healprod-gen3
    prefix: externaldata.org
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::205252583234:role/healprod--healexternaldata-helm--dashboard-access
fence:
  usersync:
    usersync: true
    userYamlS3Path: s3://cdis-gen3-users/heal/user.yaml
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::205252583234:role/healprod--healexternaldata-helm--audit-sqs-sender
  replicaCount: 4
  autoscaling:
    enabled: false
    maxReplicas: 1
    minReplicas: 1
    targetCPUUtilizationPercentage: 40
  enabled: true
  externalSecrets:
    createK8sGoogleAppSecrets: true
    fenceConfig: externaldata-fence-config
    fenceJwtKeys: externaldata-fence-jwt
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/fence
    tag: '2025.12'
global:
  pdb: true
  aws:
    account: '205252583234'
    awsEsProxyRole: healprod--healexternaldata-helm--es-access
    enabled: true
    hatchery_role: healprod--healexternaldata-helm--hatchery-sa
    secretStoreServiceAccount:
      enabled: true
      roleArn: arn:aws:iam::205252583234:role/healprod--healexternaldata-helm--external-secrets-sa
    wafv2:
      enabled: true
      wafAclArn: arn:aws:wafv2:us-east-1:205252583234:regional/webacl/healprod-waf/433ff65b-9bda-4850-b7b9-dd07051a11e3
  dev: false
  dictionaryUrl: https://s3.amazonaws.com/dictionary-artifacts/heal_dictionary/1.1.0/schema.json
  dispatcherJobNum: '10'
  environment: externaldata
  externalSecrets:
    deploy: true
    createSlackWebhookSecret: true
    slackWebhookSecretName: externaldata-slack-webhook
  hostname: externaldata.healdata.org
  fenceURL: https://externaldata.healdata.org/user
  manifestGlobalExtraValues:
    kube_bucket: kube-healprod-gen3
    logs_bucket: logs-healprod-gen3
  portalApp: gitops
  postgres:
    dbCreate: false
  revproxyArn: arn:aws:acm:us-east-1:205252583234:certificate/8bb3d424-be34-493c-a43b-e2c686c9dc6c
hatchery:
  enabled: false
indexd:
  defaultPrefix: dg.H35L/
  replicaCount: 4
  autoscaling:
    enabled: false
    maxReplicas: 1
    minReplicas: 1
    targetCPUUtilizationPercentage: 40
  enabled: true
  externalSecrets:
    serviceCreds: externaldata-indexd-service-creds
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/indexd
    tag: '2025.12'
manifestservice:
  enabled: true
  externalSecrets:
    manifestserviceG3auto: externaldata-manifestservice-g3auto
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/manifestservice
    tag: '2025.12'
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::205252583234:role/healprod--healexternaldata-helm--manifest-service-sa
metadata:
  enabled: true
  esEndpoint: http://elasticsearch:9200
  externalSecrets:
    metadataG3auto: externaldata-metadata-g3auto
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/metadata-service
    tag: '2025.12'
mutatingWebhook:
  enabled: false
peregrine:
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/peregrine
    tag: '2025.12'
portal:
  enabled: false
revproxy:
  replicaCount: 4
  autoscaling:
    enabled: false
    maxReplicas: 1
    minReplicas: 1
    targetCPUUtilizationPercentage: 40
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/nginx
    tag: '2025.12'
  ingress:
    aws:
      group: healprod
sheepdog:
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/sheepdog
    tag: '2025.12'
  replicaCount: 2
wts:
  enabled: false
