cluster: devplanetv2
project: dev

grafana-alloy:
  enabled: true
  configuration:
    enabled: false

karpenter:
  enabled: true
  targetRevision: v0.32.9
  configuration:
    enabled: true

karpenter-crds:
  amiSelectorName: "1-31-EKS-FIPS*"
  enabled: true
  selectorTag: "devplanetv2"
  migration: true
  default:
    consolidation: true
    consolidationPolicy: "whenUnderutilized"
    expireAfter: "168h"
  workflow:
    sgSelector: devplanetv2
