ambassador:
  enabled: true
  jupyterNamespace: jupyter-pods-bihstaging-helm
arborist:
  autoscaling:
    enabled: true
    maxReplicas: 1
    minReplicas: 1
    targetCPUUtilizationPercentage: 40
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/arborist
    tag: '2026.01'
audit:
  enabled: true
  externalSecrets:
    auditG3auto: bihstaging-cloudauto-audit-g3auto
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/audit-service
    tag: '2026.01'
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::533267425233:role/bihprod--bihstaging-helm--audit-sqs-receiver
manifestservice:
  enabled: false
aws-es-proxy:
  enabled: true
  esEndpoint: vpc-bihstaging-gen3-metadata-246rfk4w4ymusdypoqs2g6ml3m.us-east-1.es.amazonaws.com
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/aws-es-proxy
    tag: v1.3.1
dashboard:
  dashboardConfig:
    bucket: dashboard-533267425233-bihprod-gen3
    prefix: bih.data-commons.org
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::533267425233:role/bihprod--bihstaging-helm--dashboard-access
etl:
  esEndpoint: elasticsearch
  etlMapping:
    mappings:
      - doc_type: dataset
        name: bih_dataset
        props:
          - name: project_id
          - name: submitter_id
          - name: collection_id
          - name: commons_long_name
          - name: commons_name
          - name: data_url_doi
          - name: disease_type
          - name: full_name
          - name: license
          - name: metadata_source_date
          - name: metadata_source_version
          - name: primary_site
          - name: publication_citation
        root: dataset
        type: aggregator
      - doc_type: subject
        name: bih_subject
        parent_props:
          - path: datasets[collection_id,commons_long_name,commons_name,data_contributor,data_host,data_url_doi,disease_type,license,metadata_source_api,metadata_source_date,metadata_source_version,primary_site]
        props:
          - name: project_id
          - name: submitter_id
          - name: race
        root: subject
        type: aggregator
      - doc_type: imaging_study
        name: bih_imaging_study
        parent_props:
          - path: subjects[race,subject_id:submitter_id].datasets[collection_id,commons_long_name,commons_name,data_contributor,data_host,data_url_doi,disease_type,license,metadata_source_api,metadata_source_date,metadata_source_version,primary_site]
        props:
          - name: project_id
          - name: submitter_id
          - name: StudyDescription
          - name: StudyInstanceUID
          - name: study_viewer_url
          - name: PatientAge
          - name: PatientSex
          - name: PatientID
          - name: EthnicGroup
          - name: loinc_code
          - name: loinc_contrast
          - name: loinc_long_common_name
          - name: loinc_method
          - name: loinc_system
        root: imaging_study
        type: aggregator
      - doc_type: imaging_series
        name: bih_imaging_series
        parent_props:
          - path: imaging_studies[StudyDescription,StudyInstanceUID,PatientAge,PatientSex,PatientID,EthnicGroup].subjects[race,subject_id:submitter_id].datasets[collection_id,commons_long_name,commons_name,data_contributor,data_host,data_url_doi,disease_type,license,metadata_source_api,metadata_source_date,metadata_source_version,primary_site]
        props:
          - name: project_id
          - name: submitter_id
          - name: object_ids
          - name: BodyPartExamined
          - name: Manufacturer
          - name: Modality
          - name: SeriesDescription
          - name: SeriesInstanceUID
          - name: series_viewer_url
          - name: dicom_viewer_url
        root: imaging_series
        type: aggregator
  image:
    tube:
      tag: '2026.01'
    spark:
      tag: '2026.01'
fence:
  usersync:
    usersync: true
    userYamlS3Path: s3://cdis-gen3-users/midrc-bih-staging/user.yaml
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::533267425233:role/bihprod--bihstaging-helm--audit-sqs-sender
  autoscaling:
    enabled: true
    maxReplicas: 1
    minReplicas: 1
    targetCPUUtilizationPercentage: 40
  enabled: true
  externalSecrets:
    createK8sGoogleAppSecrets: true
    fenceConfig: bihstaging-cloudauto-fence-config
    fenceJwtKeys: bihstaging-cloudauto-fence-jwt
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/fence
    tag: '2026.01'
fluentd:
  enabled: true
  image:
    repository: fluent/fluentd-kubernetes-daemonset
    tag: v1.15.3-debian-cloudwatch-1.0
frontend-framework:
  enabled: true
  image:
    repository: quay.io/cdis/bih-data-commons
    tag: 1.3.5
global:
  aws:
    account: '533267425233'
    awsEsProxyRole: bihprod--bihstaging-helm--es-access
    enabled: true
    hatchery_role: bihprod--bihstaging-helm--hatchery-sa
    secretStoreServiceAccount:
      enabled: true
      roleArn: arn:aws:iam::533267425233:role/bihprod--bihstaging-helm--external-secrets-sa
    wafv2:
      enabled: true
      wafAclArn: arn:aws:wafv2:us-east-1:533267425233:regional/webacl/bihprod-waf/540985b3-9a4b-4d25-9881-7f1ce48d78d2
  dev: false
  dictionaryUrl: https://s3.amazonaws.com/dictionary-artifacts/bih_dictionary/0.2.1/schema.json
  dispatcherJobNum: '10'
  environment: bihstaging-cloudauto
  externalSecrets:
    deploy: true
    createSlackWebhookSecret: true
    slackWebhookSecretName: bihstaging-slack-webhook
  frontendRoot: gen3ff
  hostname: bihstaging.data-commons.org
  fenceURL: https://bihstaging.data-commons.org/user
  publicDataSets: true
  manifestGlobalExtraValues:
    kube_bucket: kube_bucket.devplanetv1.gen3
    logs_bucket: logs-devplanetv1-gen3
  tierAccessLevel: libre
  portalApp: gitops
  postgres:
    dbCreate: false
  revproxyArn: arn:aws:acm:us-east-1:533267425233:certificate/dcb6f91b-6e4c-4458-a9d7-3750ba92b754
hatchery:
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/hatchery
    tag: '2026.01'
  hatchery:
    json: |-
      {
        "user-namespace": "jupyter-pods-bihstaging-helm",
        "sub-dir": "/workspace",
        "user-volume-size": "10Gi",
        "sidecar": {
          "cpu-limit": "1.0",
          "memory-limit": "256Mi",
          "image": "quay.io/cdis/ecs-ws-sidecar:2026.01",
          "env": {
            "NAMESPACE": "default",
            "GEN3_ENDPOINT": "bihstaging.data-commons.org",
            "HOSTNAME": "bihstaging.data-commons.org"
          },
          "args": [],
          "command": [
            "/bin/bash",
            "./sidecar.sh"
          ],
          "lifecycle-pre-stop": [
            "su",
            "-c",
            "echo test",
            "-s",
            "/bin/sh",
            "root"
          ]
        },
        "containers": [
          {
            "target-port": 8888,
            "cpu-limit": "1.0",
            "memory-limit": "2Gi",
            "name": "(Generic) Jupyter Lab Notebook with R Kernel",
            "image": "quay.io/cdis/jupyter-superslim-r:2.0.1",
            "env": {
              "FRAME_ANCESTORS": "bihstaging.data-commons.org"
            },
            "args": [
              "--JupyterNotebookApp.base_url=/lw-workspace/proxy/",
              "--JupyterNotebookApp.default_url=/lab",
              "--JupyterNotebookApp.password=''",
              "--JupyterNotebookApp.token=''",
              "--JupyterNotebookApp.ip='*'",
              "--JupyterNotebookApp.notebook_dir='/home/jovyan'",
              "--JupyterNotebookApp.shutdown_no_activity_timeout=5400",
              "--JupyterNotebookApp.quit_button=False"
            ],
            "command": [
              "start-notebook.sh"
            ],
            "path-rewrite": "/lw-workspace/proxy/",
            "use-tls": "false",
            "ready-probe": "/lw-workspace/proxy/",
            "lifecycle-post-start": [
              "/bin/sh",
              "-c",
              "export IAM=`whoami`; rm -rf /home/$IAM/pd/dockerHome; rm -rf /home/$IAM/pd/lost+found; ln -s /data /home/$IAM/; rm /home/$IAM/pd/data; wget -O /data/external_data_download.ipynb https://raw.githubusercontent.com/uc-cdis/heal-platform-sdk/refs/heads/master/notebooks/external_data_download.ipynb; true"
            ],
            "user-uid": 1000,
            "fs-gid": 100,
            "user-volume-location": "/home/jovyan/pd",
            "gen3-volume-location": "/home/jovyan/.gen3"
          },
          {
            "target-port": 8888,
            "cpu-limit": "1.0",
            "memory-limit": "2Gi",
            "name": "BIH Tutorial Jupyter Notebook",
            "image": "quay.io/cdis/jupyter-notebook:bih-master",
            "env": {
              "FRAME_ANCESTORS": "bihstaging.data-commons.org",
              "JUPYTER_ENABLE_LAB": "yes"
            },
            "args": [
              "--ServerApp.base_url=/lw-workspace/proxy/",
              "--ServerApp.default_url=/lab",
              "--ServerApp.password=''",
              "--ServerApp.token=''",
              "--ServerApp.ip='*'",
              "--ServerApp.root_dir='/home/jovyan'",
              "--ServerApp.shutdown_no_activity_timeout=5400",
              "--ServerApp.quit_button=False"
            ],
            "command": [
              "start-notebook.sh"
            ],
            "path-rewrite": "/lw-workspace/proxy/",
            "use-tls": "false",
            "ready-probe": "/lw-workspace/proxy/",
            "lifecycle-post-start": [
              "/bin/sh",
              "-c",
              "export IAM=`whoami`; rm -rf /home/$IAM/pd/dockerHome; rm -rf /home/$IAM/pd/lost+found; ln -s /data /home/$IAM/; rm /home/$IAM/pd/data; wget -O /data/external_data_download.ipynb https://raw.githubusercontent.com/uc-cdis/heal-platform-sdk/refs/heads/master/notebooks/external_data_download.ipynb; true"
            ],
            "user-uid": 1000,
            "fs-gid": 100,
            "user-volume-location": "/home/jovyan/pd",
            "gen3-volume-location": "/home/jovyan/.gen3"
          }
        ]
      }
guppy:
  configIndex: bih_array-config
  enabled: true
  esEndpoint: http://elasticsearch:9200
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/guppy
    tag: '2026.01'
  indices:
    - index: bih_dataset
      type: dataset
    - index: bih_subject
      type: subject
    - index: bih_imaging_study
      type: imaging_study
    - index: bih_imaging_series
      type: imaging_series
indexd:
  defaultPrefix: dg.MD1RBIH/
  autoscaling:
    enabled: true
    maxReplicas: 1
    minReplicas: 1
    targetCPUUtilizationPercentage: 40
  enabled: true
  externalSecrets:
    serviceCreds: bihstaging-cloudauto-indexd-service-creds
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/indexd
    tag: '2026.01'
metadata:
  autoscaling:
    enabled: true
    maxReplicas: 1
    minReplicas: 1
    targetCPUUtilizationPercentage: 40
  enabled: true
  esEndpoint: http://elasticsearch:9200
  externalSecrets:
    metadataG3auto: bihstaging-cloudauto-metadata-g3auto
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/metadata-service
    tag: '2026.01'
peregrine:
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/peregrine
    tag: '2026.01'
portal:
  enabled: true
  customConfig:
    enabled: true
    dir: bihprod/bih-staging.data-commons.org/values/portal/
    repo: https://github.com/uc-cdis/gen3-gitops.git
    branch: master
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/data-portal
    tag: '2026.01'
requestor:
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/requestor
    tag: '2026.01'
revproxy:
  autoscaling:
    enabled: true
    maxReplicas: 1
    minReplicas: 1
    targetCPUUtilizationPercentage: 40
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/nginx
    tag: '2026.01'
  ingress:
    aws:
      group: bihprod
sheepdog:
  enabled: true
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/sheepdog
    tag: '2026.01'
ssjdispatcher:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::533267425233:role/gen3_service/bihprod--bihstaging-cloudauto--ssj
  jobServiceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::533267425233:role/gen3_service/bihprod--bihstaging-cloudauto--ssj-job
  enabled: true
  externalSecrets:
    credsFile: bihstaging-cloudauto-ssjdispatcher-creds
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/ssjdispatcher
    tag: '2026.01'
  indexing: quay.io/cdis/indexs3client:2026.01
wts:
  enabled: true
  externalSecrets:
    createWtsOidcClientSecret: false
    wtsG3auto: bihstaging-cloudauto-wts-g3auto
    wtsOidcClient: bihstaging-cloudauto-wts-client-secret
  image:
    repository: 707767160287.dkr.ecr.us-east-1.amazonaws.com/gen3/workspace-token-service
    tag: '2026.01'
